using System.Text.Json;
using System.Text.RegularExpressions;

namespace AgentOrchestrator.CodeQuality;

/// <summary>An item omitted while deriving a repository hierarchy.</summary>
public sealed record ScopeExclusion(string Path, string Reason);

internal enum ScopeRuleAction
{
    Include,
    Exclude,
}

internal sealed record ScopeDecision(bool Included, string? Reason);

/// <summary>
/// Applies built-in, .gitignore, and repository-curated scope rules to canonical
/// repository-relative paths. Rules use case-sensitive Git wildmatch syntax.
/// </summary>
internal sealed class RepositoryScope
{
    internal const string ConfigurationPath = ".quality/scope.json";

    private static readonly (string Pattern, string Reason)[] Defaults =
    [
        (".quality/**", "Quality Studio metadata"),
        ("**/.quality/**", "Quality Studio metadata"),
        (".git/**", "Git metadata"),
        ("**/.git/**", "Git metadata"),
        ("**/*.review-meta.*.json", "Review metadata sidecar"),
        ("**/bin/**", "Compiler build output"),
        ("**/obj/**", "Compiler build output"),
        ("**/node_modules/**", "Package cache"),
        ("**/packages/**", "Package cache"),
        ("**/.nuget/**", "Package cache"),
        ("**/.pnpm-store/**", "Package cache"),
        ("**/*.g.cs", "Generated source"),
        ("**/*.g.i.cs", "Generated source"),
        ("**/*.generated.cs", "Generated source"),
        ("**/TemporaryGeneratedFile_*.cs", "Generated source"),
    ];

    private readonly string root;
    private readonly IReadOnlyList<ScopeRule> rules;

    private RepositoryScope(string root, IReadOnlyList<ScopeRule> rules)
    {
        this.root = root;
        this.rules = rules;
    }

    public string? ConfigurationFile => File.Exists(Path.Combine(root, ConfigurationPath.Replace('/', Path.DirectorySeparatorChar)))
        ? ConfigurationPath
        : null;

    public static RepositoryScope Load(string repositoryRoot)
    {
        var root = Path.GetFullPath(repositoryRoot);
        var rules = new List<ScopeRule>();
        foreach (var (pattern, reason) in Defaults)
        {
            rules.Add(new ScopeRule(ScopeRuleAction.Exclude, pattern, ".", reason));
        }

        LoadGitIgnoreRules(root, rules);
        LoadCuratedRules(root, rules);
        return new RepositoryScope(root, rules);
    }

    public ScopeDecision Evaluate(string repositoryRelativePath, string? absolutePath = null)
    {
        var path = Canonical(repositoryRelativePath);
        ScopeRule? winner = null;
        foreach (var rule in rules)
        {
            if (rule.IsMatch(path)) winner = rule;
        }

        // The conventional generated-file marker is a built-in default. Git and
        // curated rules still win because they are evaluated after this virtual rule.
        var generated = absolutePath is not null && IsGeneratedSource(absolutePath);
        if (generated && (winner is null || winner.SourceKind == RuleSourceKind.Default))
        {
            winner = new ScopeRule(ScopeRuleAction.Exclude, path, ".", "Generated source");
        }

        // Re-evaluate non-default rules so an explicit .gitignore negation or a
        // curated include can override generated-source detection.
        if (generated)
        {
            foreach (var rule in rules.Where(rule => rule.SourceKind != RuleSourceKind.Default))
            {
                if (rule.IsMatch(path)) winner = rule;
            }
        }

        return winner?.Action == ScopeRuleAction.Exclude
            ? new ScopeDecision(false, winner.Reason)
            : new ScopeDecision(true, null);
    }

    private static bool IsGeneratedSource(string path)
    {
        if (!Path.GetExtension(path).Equals(".cs", StringComparison.OrdinalIgnoreCase) || !File.Exists(path)) return false;
        using var reader = new StreamReader(path);
        for (var lineNumber = 0; lineNumber < 5 && reader.ReadLine() is { } line; lineNumber++)
        {
            if (line.Contains("<auto-generated", StringComparison.OrdinalIgnoreCase)) return true;
        }
        return false;
    }

    private static void LoadGitIgnoreRules(string root, List<ScopeRule> rules)
    {
        var ignoreFiles = Directory.EnumerateFiles(root, ".gitignore", new EnumerationOptions
        {
            RecurseSubdirectories = true,
            AttributesToSkip = FileAttributes.ReparsePoint,
        }).OrderBy(path => Path.GetRelativePath(root, path).Count(character => character is '/' or '\\'))
          .ThenBy(path => path, StringComparer.Ordinal);

        foreach (var ignoreFile in ignoreFiles)
        {
            var relativeIgnore = Canonical(Path.GetRelativePath(root, ignoreFile));
            var priorGitRule = rules.LastOrDefault(rule =>
                rule.SourceKind == RuleSourceKind.GitIgnore && rule.IsMatch(relativeIgnore));
            if (priorGitRule?.Action == ScopeRuleAction.Exclude) continue;
            var basePath = Canonical(Path.GetDirectoryName(relativeIgnore) ?? ".");
            var lines = File.ReadAllLines(ignoreFile);
            for (var index = 0; index < lines.Length; index++)
            {
                var parsed = ParseGitIgnoreLine(lines[index]);
                if (parsed is null) continue;
                var (action, pattern) = parsed.Value;
                rules.Add(new ScopeRule(action, pattern, basePath,
                    $"Ignored by {relativeIgnore}:{index + 1} ({pattern})", RuleSourceKind.GitIgnore));
            }
        }
    }

    private static (ScopeRuleAction Action, string Pattern)? ParseGitIgnoreLine(string line)
    {
        line = TrimUnescapedTrailingSpaces(line);
        if (line.Length == 0 || line[0] == '#') return null;
        if (line.StartsWith("\\#", StringComparison.Ordinal)) line = line[1..];
        var action = ScopeRuleAction.Exclude;
        if (line[0] == '!')
        {
            action = ScopeRuleAction.Include;
            line = line[1..];
        }
        else if (line.StartsWith("\\!", StringComparison.Ordinal))
        {
            line = line[1..];
        }
        return line.Length == 0 ? null : (action, line);
    }

    private static string TrimUnescapedTrailingSpaces(string value)
    {
        var end = value.Length;
        while (end > 0 && value[end - 1] == ' ' && (end < 2 || value[end - 2] != '\\')) end--;
        return value[..end].Replace("\\ ", " ", StringComparison.Ordinal);
    }

    private static void LoadCuratedRules(string root, List<ScopeRule> rules)
    {
        var path = Path.Combine(root, ConfigurationPath.Replace('/', Path.DirectorySeparatorChar));
        if (!File.Exists(path)) return;

        using var document = JsonDocument.Parse(File.ReadAllText(path), new JsonDocumentOptions
        {
            AllowTrailingCommas = false,
            CommentHandling = JsonCommentHandling.Disallow,
        });
        if (document.RootElement.ValueKind != JsonValueKind.Object ||
            !document.RootElement.TryGetProperty("rules", out var configuredRules) ||
            configuredRules.ValueKind != JsonValueKind.Array)
        {
            throw new InvalidDataException($"{ConfigurationPath} must contain a 'rules' array.");
        }
        if (document.RootElement.EnumerateObject().Any(property => property.Name is not ("$schema" or "rules")))
        {
            throw new InvalidDataException($"{ConfigurationPath} contains an unsupported property.");
        }

        var index = 0;
        foreach (var configuredRule in configuredRules.EnumerateArray())
        {
            index++;
            if (configuredRule.ValueKind != JsonValueKind.Object ||
                !configuredRule.TryGetProperty("action", out var actionElement) ||
                actionElement.ValueKind != JsonValueKind.String ||
                !configuredRule.TryGetProperty("pattern", out var patternElement) ||
                patternElement.ValueKind != JsonValueKind.String)
            {
                throw new InvalidDataException($"{ConfigurationPath} rule {index} requires string 'action' and 'pattern' properties.");
            }
            var actionText = actionElement.GetString();
            var pattern = patternElement.GetString();
            var action = actionText switch
            {
                "include" => ScopeRuleAction.Include,
                "exclude" => ScopeRuleAction.Exclude,
                _ => (ScopeRuleAction?)null,
            };
            if (action is null || string.IsNullOrWhiteSpace(pattern))
            {
                throw new InvalidDataException($"{ConfigurationPath} rule {index} has an invalid action or empty pattern.");
            }
            if (configuredRule.EnumerateObject().Any(property => property.Name is not ("action" or "pattern" or "reason")))
            {
                throw new InvalidDataException($"{ConfigurationPath} rule {index} contains an unsupported property.");
            }
            string? reason = null;
            if (configuredRule.TryGetProperty("reason", out var reasonElement))
            {
                if (reasonElement.ValueKind != JsonValueKind.String)
                    throw new InvalidDataException($"{ConfigurationPath} rule {index} reason must be a string.");
                reason = reasonElement.GetString();
            }
            if (action == ScopeRuleAction.Exclude && string.IsNullOrWhiteSpace(reason))
            {
                throw new InvalidDataException($"{ConfigurationPath} exclude rule {index} requires a non-empty reason.");
            }
            if (reason?.Length > 500)
                throw new InvalidDataException($"{ConfigurationPath} rule {index} reason must be at most 500 characters.");
            rules.Add(new ScopeRule(action.Value, pattern!, ".", reason?.Trim() ?? string.Empty, RuleSourceKind.Curated));
        }
    }

    private static string Canonical(string path) => path.Replace('\\', '/').TrimStart('/').TrimEnd('/') is { Length: > 0 } value
        ? value
        : ".";

    private enum RuleSourceKind
    {
        Default,
        GitIgnore,
        Curated,
    }

    private sealed class ScopeRule
    {
        private readonly Regex matcher;

        public ScopeRule(ScopeRuleAction action, string pattern, string basePath, string reason,
            RuleSourceKind sourceKind = RuleSourceKind.Default)
        {
            Action = action;
            Reason = reason;
            SourceKind = sourceKind;
            matcher = new Regex(ToRegex(pattern, basePath), RegexOptions.CultureInvariant | RegexOptions.NonBacktracking);
        }

        public ScopeRuleAction Action { get; }
        public string Reason { get; }
        public RuleSourceKind SourceKind { get; }
        public bool IsMatch(string path)
        {
            if (matcher.IsMatch(path)) return true;
            for (var separator = path.LastIndexOf('/'); separator > 0; separator = path.LastIndexOf('/', separator - 1))
            {
                if (matcher.IsMatch(path[..separator])) return true;
            }
            return false;
        }

        private static string ToRegex(string rawPattern, string basePath)
        {
            var directoryOnly = rawPattern.EndsWith("/", StringComparison.Ordinal);
            var pattern = rawPattern.TrimEnd('/');
            var anchored = pattern.StartsWith("/", StringComparison.Ordinal);
            pattern = pattern.TrimStart('/');
            var hasSlash = pattern.Contains('/', StringComparison.Ordinal);
            var prefix = basePath == "." ? string.Empty : Regex.Escape(basePath) + "/";

            var builder = new System.Text.StringBuilder("^");
            if (anchored || hasSlash)
            {
                builder.Append(prefix);
            }
            else
            {
                builder.Append(prefix).Append("(?:.*/)?");
            }
            AppendWildmatch(builder, pattern);
            if (directoryOnly || !hasSlash) builder.Append("(?:/.*)?");
            builder.Append('$');
            return builder.ToString();
        }

        private static void AppendWildmatch(System.Text.StringBuilder builder, string pattern)
        {
            for (var index = 0; index < pattern.Length; index++)
            {
                var character = pattern[index];
                if (character == '*')
                {
                    var doubleStar = index + 1 < pattern.Length && pattern[index + 1] == '*';
                    if (!doubleStar)
                    {
                        builder.Append("[^/]*");
                        continue;
                    }
                    while (index + 1 < pattern.Length && pattern[index + 1] == '*') index++;
                    if (index + 1 < pattern.Length && pattern[index + 1] == '/')
                    {
                        index++;
                        builder.Append("(?:.*/)?");
                    }
                    else
                    {
                        builder.Append(".*");
                    }
                    continue;
                }
                if (character == '?')
                {
                    builder.Append("[^/]");
                    continue;
                }
                if (character == '[')
                {
                    var close = pattern.IndexOf(']', index + 1);
                    if (close > index + 1)
                    {
                        var content = pattern[(index + 1)..close];
                        builder.Append('[');
                        if (content[0] is '!' or '^')
                        {
                            builder.Append('^');
                            content = content[1..];
                        }
                        builder.Append(content.Replace("\\", "\\\\", StringComparison.Ordinal)).Append(']');
                        index = close;
                        continue;
                    }
                }
                if (character == '\\' && index + 1 < pattern.Length)
                {
                    character = pattern[++index];
                }
                builder.Append(Regex.Escape(character.ToString()));
            }
        }
    }
}
