version: 2
updates:
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    groups:
      angular-patches:
        applies-to: version-updates
        patterns:
          - "@angular/*"
        update-types:
          - patch

  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    groups:
      nuget-patches:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
