using System.Text.Json;

namespace AgentOrchestrator.CodeQuality.Tests;

public sealed class RepositoryScopeConfigurationStoreTests
{
    [Fact]
    public void Exact_exclude_is_atomic_ordered_and_removable()
    {
        using var root = new TemporaryRoot();
        var store = new RepositoryScopeConfigurationStore(root.Path);
        var files = new[] { "src/A.cs", "src/B.cs" };

        var created = store.Add(new RepositoryScopeRule("exclude", "src/A.cs", "Generated by an external tool."),
            files, confirmExpansion: false);

        var rule = Assert.Single(created.Rules);
        Assert.Equal("src/A.cs", rule.Pattern);
        Assert.Equal(new[] { "src/A.cs" }, store.Preview(rule, files).MatchedFiles);
        var configurationPath = Path.Combine(root.Path, ".quality", "scope.json");
        using (var json = JsonDocument.Parse(File.ReadAllText(configurationPath)))
        {
            Assert.Equal(RepositoryScopeConfigurationStore.Schema, json.RootElement.GetProperty("$schema").GetString());
            Assert.Equal("exclude", json.RootElement.GetProperty("rules")[0].GetProperty("action").GetString());
        }
        Assert.Empty(Directory.EnumerateFiles(Path.GetDirectoryName(configurationPath)!, "*.tmp"));

        var updated = store.Update(0, new RepositoryScopeRule("include", "src/B.cs"), files,
            confirmExpansion: false);
        Assert.Equal("include", Assert.Single(updated.Rules).Action);
        Assert.Equal("src/B.cs", updated.Rules[0].Pattern);

        Assert.Empty(store.Delete(0).Rules);
        Assert.Empty(store.Read().Rules);
    }

    [Fact]
    public void Wider_pattern_requires_preview_confirmation_and_exclude_reason()
    {
        using var root = new TemporaryRoot();
        var store = new RepositoryScopeConfigurationStore(root.Path);
        var files = new[] { "src/A.cs", "src/B.cs", "tests/A.cs" };
        var rule = new RepositoryScopeRule("exclude", "src/*.cs", "Reviewed elsewhere.");

        var preview = store.Preview(rule, files);
        Assert.True(preview.WiderPattern);
        Assert.Equal(new[] { "src/A.cs", "src/B.cs" }, preview.MatchedFiles);
        Assert.Throws<ArgumentException>(() => store.Add(rule, files, confirmExpansion: false));
        Assert.Single(store.Add(rule, files, confirmExpansion: true).Rules);
        Assert.Throws<ArgumentException>(() => store.Add(
            new RepositoryScopeRule("exclude", "tests/A.cs"), files, confirmExpansion: false));
    }

    private sealed class TemporaryRoot : IDisposable
    {
        public TemporaryRoot()
        {
            Path = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "quality-scope-tests", Guid.NewGuid().ToString("N"));
            Directory.CreateDirectory(Path);
        }

        public string Path { get; }
        public void Dispose() => TestDirectory.Delete(Path);
    }
}
